### PR TITLE
Remove loadMigrationsFrom method from ServiceProvider.

### PR DESCRIPTION
**Pull request by omerkoseoglu**

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Hi @omerkoseoglu, thanks for the pull request! I'm just wondering what the purpose of it is?

**Comment by omerkoseoglu** [comment]
> Hi @omerkoseoglu, thanks for the pull request! I'm just wondering what the purpose of it is?

Hi @ash-jc-allen, 

I use a multi-tenant model in the system. In most libraries, migrations are free because they are migrated by the developer. I can move migration files to a new subfolder in migrations folder. I may not need the tables for the package in the main database. I can only use the package in tenant databases. Sorry for my english

**Comment by ash-jc-allen** [comment]
Hi @omerkoseoglu, unfortunately at the moment, this isn't something that's really in the scope of the package sorry. However, if it might be something that will be added in the future versions of it to handle situations like these.

**Comment by jaulz** [comment]
@ash-jc-allen any chance to reopen this? 😊  I think migrations should be handled by developers, too, and running "artisan migrate" shouldn't be a big deal for anyone?

**Comment by ash-jc-allen** [comment]
@jaulz It's pretty funny you ask this question, I was actually thinking about reopening this over the weekend. After doing a bit of reading up, I agree with @omerkoseoglu that we probably shouldn't be loading the migrations through the service provider, but instead providing them for publishing.

I'll need to have a quick tinker and update the documentation, but I don't think there'll be any problem with getting this updated in the next few days :smile:

**Comment by jaulz** [comment]
@ash-jc-allen cool, sounds promising! 😊  And thanks a lot for this great package!

**Comment by ash-jc-allen** [comment]
@jaulz It's no problem at all, I'm glad that you're liking it. If you've got any suggestions for possible improvements or changes, I'd be happy to hear about them for future updates!

**Comment by ash-jc-allen** [comment]
Just dropping a quick message here to let you know that these changes have now been included in a new v5.0.0 release (https://github.com/ash-jc-allen/short-url/releases/tag/v5.0.0).

**Pull request merged**
