### PR TITLE
fix: Add foreign key name to belongsTo relationship (fixes #131)

### LINKED ISSUE #131: ShortURLVisit BelongsTo relationship foreign key incorrect
I noticed when working with Laravel Nova that the inverse relationship `ShortURLVisit::shortURL()` doesn't appear to be working correctly. This is the line:

https://github.com/ash-jc-allen/short-url/blob/53df9e3c6c27bbfc949e8719bcd2016b3d95e3dc/src/Models/ShortURLVisit.php#L86

I think this is because the foreign key is calculated by converting ShortURL into it's snake-case equivalent and adding `_id` which becomes `short_u_r_l_id` (see, <https://laravel.com/docs/9.x/eloquent-relationships#one-to-one-defining-the-inverse-of-the-relationship>).

Adding the foreign key name fixed the problem:

        return $this->belongsTo(ShortURL::class, 'short_url_id');

Will create a PR for this shortly if you like.

### PR DESCRIPTION
**Pull request by pointybeard**

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Hey @pointybeard, thanks for this PR! 😄

I'm a little bit confused by the fact that no one has picked up on this before (including me haha!). I've just added a test to show the bug exists and that your change fixes it: https://github.com/ash-jc-allen/short-url/commit/9fa532aa9e16a2727df033e2c95f0f03309406ef

I'm wondering whether this could be classed as a breaking change because it could potentially break existing apps using this relationship (even if it is broken). Do you have any thoughts on that?

**Comment by jaetoole** [comment]
@ash-jc-allen I think this is safe to merge. It's proven via your test that the bug exists on master which means that the method is not performing as expected (and won't give the required results). This fix fixes that which I don't believe constitutes towards a breaking change.

**Comment by ash-jc-allen** [comment]
Thanks for the input on it @jaetoole. I think you're right and that it's probably safe for just a patch release. I think I'm just being paranoid and scared that I'm going to break a load of projects that are in the wild haha.

@pointybeard I'll get this merged later today and hopefully get it out in a release soon 🙂

**Comment by pointybeard** [comment]
@ash-jc-allen great, thanks a lot! On the issue of this being a potential breaking change, I think @jaetoole is right. All that will happen is something that wasn't working will now work. I.e. an empty collection now has records.

**Comment by pointybeard** [comment]
FYI I rebased my branch to include the test you added, @ash-jc-allen.

**Comment by ash-jc-allen** [comment]
Hey @pointybeard! These changes are now available in v7.1.0 (https://github.com/ash-jc-allen/short-url/releases/tag/v7.1.0). Thanks again! 😄

**Pull request merged**
