### PR TITLE
getAppDomain method, updates routes method

### PR DESCRIPTION
**Pull request by johnpaulmedina**
- Adds new public method for returning the applications domain.
- Adds domain to the default routes method

### CODE REVIEW

**Comment by johnpaulmedina** [comment]
Here is a PR that will incorporate the domain in the routes method of ShortURL Builder class. As you can see nothing really changes, and does not require additional code or configuration by an end-user.

By adding these methods this package by default will now allow for Laravel application to operate with multiple domains.

IE: single use domain
Package will continue to work as intended, will define the routes as configured. End user will be able to use `somedomain.com/short/{urlKey}`

IE: multiple use domain
Package will also work as intended. When a user overwrites their `default_url` in the configuration file now the routes are specific to that domain only. This will eliminate the application from interfering with additional configured routes. Now the application responds for all routes, without the need for creating custom routes.

- Example domain: `bitly.com` (Primary app url)
- Example domain: `bit.ly` (Secondary short app domain)

**Comment by ash-jc-allen** [comment]
Hey, thanks for the PR! Am I right in assuming that if a dev wanted their short URL to work on both domains (e.g - `bitly.com` and `bit.ly`), this change would prevent that from working? It would now only work on the `bit.ly` (assuming that this domain was the one provided as the `short-url.default_url` config field? 🙂

**Comment by johnpaulmedina** [comment]
Interesting. Yes, you would be correct. What could be nice, is allowing for either a single string value or an array of domains. Than for each domain or if only a single string domain then it can register the routes as intended.

Would you like me to update the PR for that? I think this would be the best config out the box (in my opinion). Allows the application to respond to multiple domains, minimizes the need to setup custom routes when using additional domains.

What do you think? I wanted to respect keeping the package lean as you stated but minimize setup time and follow a more standard approach to short urls.

**Comment by johnpaulmedina** [comment]
I am doing some thinking now. Realistically the package currently only writes the one domain to the database. I personally have not tested it but I am wondering, it should still respond regardless of the domain currently because of the actual `url_key` that is defined on the table and because you did not specify a domain on your routes method. What was the need to for the column `default_short_url` in the database? Is that just for displaying the short url list? I did not see that column being used anywhere in the src code.

**Comment by ash-jc-allen** [comment]
Yeah I feel like this might be opening a can of warms and would only be beneficial to a small number of projects using this package.

I think I'll hold off on adding this feature, and think it should probably be implemented by the developer in the app code on a project-by-project basis. However, if enough people want this, I'll be happy to maybe revisit it.

Huge thanks for taking the time to make the PR though. It's definitely given me some food for thought! 😄

**Pull request closed without merging**
