### PR TITLE
made the url_key unique and changed destination_url into TEXT

### PR DESCRIPTION
**Pull request by Victor-emil**
This PR makes the url_key column unique in the database. Currently the code tries to take care of duplicate entries, but when you have a couple of jobs running you might run into situations where two concurrent jobs considers the same key to be available (race condition). To mitigate this I would appreciate if the database would throw an error by using a unique index. This was I can catch the exception in a try catch. This will also make the searches faster when retrieving the key in the ShortURLController. 

The PR also changes the destination_url column into TEXT which allows for urls that takes up more space than the allowed current varchar(255) column. We have a lot of urls that contains UTM parameters which can take up more space.

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Hey @Victor-emil! Thanks for the PR (and don't worry, I've not forgotten about the other one) :smile: 

I totally agree with the idea behind these changes. Would you mind maybe making these to the original migration that creates the `short_urls` table instead though (https://github.com/ash-jc-allen/short-url/blob/master/database/migrations/2019_12_22_015115_create_short_urls_table.php)?

My main reasoning behind it is that we don't know if anyone's already added the unique index themselves. So, I don't feel too comfortable adding migrations that might cause people any issues. But by putting it in the original migration, it means that any new projects using this package will get to make use of the indexes and column change.

I'm guessing you probably already have, but of course, if you need to make these changes yourself, feel free to publish the migrations and make your own changes there.

**Comment by Victor-emil** [comment]
@ash-jc-allen. Makes sense. I will do that asap. 👍 

Yes I already adjusted the tabel in my own code. 😀

**Comment by ash-jc-allen** [comment]
@Victor-emil Perfect, thanks! :smile:

**Comment by Victor-emil** [comment]
@ash-jc-allen. Done!😎

**Comment by ash-jc-allen** [comment]
Hey @Victor-emil! I'm just dropping you a quick message on this PR too, to let you know that I've just tagged these changes in the `v.5.2.0` release. Thanks again for the PR on this one! :smile: 

https://github.com/ash-jc-allen/short-url/releases/tag/v5.2.0

**Pull request merged**
