### PR TITLE
Add Middleware, URL, Domain and Empty Prefix features

### PR DESCRIPTION
**Pull request by afiqiqmal**
This PR is provide custom url and domain, middleware and flexible prefix to this package. This PR testing already included in the Test case.

### CODE REVIEW

**Comment by ash-jc-allen** [comment]
Hey @afiqiqmal, thanks for the PR! I've not really got any plans at the moment to allow changing the domain, but I like the idea of adding the middleware and changing the prefix.

There's already another PR open (which I need to take a look at) that's handling the prefix side of thins. Could you maybe change this PR so that it only adds the middleware, please?

If you can do that, I'll probably be able to get this merged at some point this week 😄

**Comment by Victor-emil** [comment]
This is really cool. This PR basically addresses the same points as in my PR. Changing the domain is exactly what I am also trying to achieve in my application.

**Comment by Akecel** [comment]
I was just filled with joy before falling back into sadness 😂

I think this PR is really a good idea ! With default values it can be very simple to use for a developer who would only have a simple use. But when it is used in production for a commercial product, there is a real need for customization. And this is exactly what I need for a new feature 😅

I could indeed just use a custom route built on the fly when I need it, but the fact that it is not registered in DB is rather annoying, and it makes the code a bit heavy for not much 😕
Especially since I disable the default route in my configuration, so this value is not usefull anymore and will be just a dead field in the DB.

Another solution would be to customize my migration to add a custom field that would be set by default when creating an entry with an observer. I think this is the cleanest solution when you want to have this value in DB

Let me know if you decide to accept this PR because I think it would really be the little extra that makes dev happy 😁

**Comment by afiqiqmal** [comment]
@Akecel You can achieve with `ShortURL::observe(ShortURLObserver::class);` in provider without overwrite model

**Comment by Akecel** [comment]
> @Akecel You can achieve with `ShortURL::observe(ShortURLObserver::class);` in provider without overwrite model

@afiqiqmal, Oh yeah, I had forgotten that it was possible to do this. Thanks a lot for your answer!

**Comment by ash-jc-allen** [comment]
I'm closing this PR in favour of https://github.com/ash-jc-allen/short-url/pull/121 :)

**Pull request closed without merging**
