### PR TITLE
made the alphabet input argument for hashids configurable

### PR DESCRIPTION
**Pull request by Victor-emil**

### CODE REVIEW

**Comment by Victor-emil** [comment]
Hi @ash-jc-allen. Thanks for the quick response. We were actually using a paid service for building short urls. One feature the service had was to control the allowed characters for the output keys. For our specific use case we do not want uppercase characters as part of the keys. We are sending physical mails that contains a QR-code, but also a printed url (The short url generated by this tool) and this url has to be as easy to type as possible. 🙂

**Comment by ash-jc-allen** [comment]
@Victor-emil Ahh, that makes total sense and I can definitely see the use case for it.

It's been a while since I first made this package so I'll need to refresh myself on some of the internals. But (thinking out loud here), I'm wondering whether it'd also be helpful to add this on a case-by-case basis too. So, you can still have a 'global' custom alphabet in your config, but override it when building a new URL?

e.g. - 

```php
$builder = new \AshAllenDesign\ShortURL\Classes\Builder();

$shortURLObject = $builder->destinationUrl('https://destination.com')->alphabet('alphabet-goes-here')->make();
```

If this is something that I (or anyone else) can add, would it be helpful for you at all? 😄

**Comment by ash-jc-allen** [comment]
@Victor-emil With regards to not being able to override the KeyGenerator properly. I think that part probably needs a bit of an update. It's been a while since I first wrote this package, so there's a few things I'd like to change at some point.

For the `KeyGenerator`, I'd prefer it to implement a contract so that anyone can write their own key generating implementation and pass it to the `Builder`. I'd also prefer to make the hash IDs field protected rather than private. I might get around to these changes soon at some point :)

**Comment by Victor-emil** [comment]
@ash-jc-allen. For our use case we will definitely use the configured option, since we will never change it runtime. However, I can definitely see a use case for setting the alphabet runtime (Plus I love the builder/fluent pattern)👌. 

I like that the KeyGenerator can be injected into the Builder, since we might make a couple of other tweaks. So making the hashids property overridable would be very nice. Either by making it protected or having a setHashIds method on the class. 

Just started using this package yesterday, so really happy for the fast response and great ideas😁.

**Comment by ash-jc-allen** [comment]
Hey @Victor-emil! I'm just dropping you a quick message to let you know that I've just tagged these changes in the `v.5.2.0` release. Thanks again for the contribution! :smile: 

https://github.com/ash-jc-allen/short-url/releases/tag/v5.2.0

**Pull request merged**
